### PR TITLE
Changes needed for BoneJ

### PR DESCRIPTION
**Pull request by rimadoma**
Added changes that BoneJ needs to use the AnalyzeSkeleton_ plugin as a Maven dependency.

These are:
* Dialog settings persistence between sessions (dialog remembers previous run)
* Bug fixes
* Renamed package

### CODE REVIEW

**Comment by hinerm** [comment]
@iarganda @rimadoma I don't know anything about this plugin but overall these changes seem reasonable to me.

Some notes/questions:
* the package moving is a [backwards-incompatible change](http://imagej.net/Versioning). Are there any components that use `Analyze_Skeleton` as a dependency that would have to be updated? Also - it isn't necessary but is helpful to pre-emptively bump the POM version (to `3.0.0-SNAPSHOT` in this case) to avoid accidentally releasing another `2.x.x` version.
* Are there any cases where duplicating images would defy expectations of the user and cause confusion? Do the NPEs come because the plugin is interactive and the image can be modified during execution..? (in which case a duplicate may not be appropriate...)

**Comment by rimadoma** [comment]
@hinerm We had a discussion with @mdoube and @ctrueden  about creating a naming convention for Fiji plugin packages, so I was just being "proactive" here.

The NPEs happen because the plugin is interactive. The problem was that if you show an image, and then the user closes it, its stack gets wiped clean, i.e. the input image to the plugin becomes null.

The duplications duplicate the image being processed each time an intermediate step is going to be displayed to the user. The duplicates get displayed, and the input image still gets processed by the plugin.

**Comment by iarganda** [comment]
Hello @rimadoma and @hinerm I also think the changes are reasonable. As far as I know, only the Simple Neurite Tracer makes use of AnalyzeSkeleton, so it should get updated accordingly too.

**Comment by hinerm** [comment]
>@hinerm We had a discussion with @mdoube and @ctrueden about creating a naming convention for Fiji plugin packages, so I was just being "proactive" here.

Yes definitely.. I think it's an improvement, just pointing out that dependencies need to be updated. :smile: 

>The duplicates get displayed, and the input image still gets processed by the plugin. 

Makes sense to me. Thanks for the explanation!

> As far as I know, only the Simple Neurite Tracer makes use of AnalyzeSkeleton, so it should get updated accordingly too.

yep, [SNT](https://github.com/fiji/Simple_Neurite_Tracer) and [Volume_Calculator](https://github.com/fiji/Volume_Calculator) will need to be updated.

**Pull request merged**
